"""empty message

Revision ID: 2152e3410da3
Revises: f45bbbb5a1b2
Create Date: 2024-10-04 11:00:01.202712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2152e3410da3'
down_revision = 'f45bbbb5a1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crop_management', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=400),
               existing_nullable=True)

    with op.batch_alter_table('cropcycle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planting_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('expecetd_harvest_date', sa.Date(), nullable=True))
        batch_op.drop_column('planting_dates')
        batch_op.drop_column('harvest_dates')

    with op.batch_alter_table('financial_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('details', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.drop_column('revenue')
        batch_op.drop_column('labor_cost')
        batch_op.drop_column('pesticide_cost')
        batch_op.drop_column('seed_cost')
        batch_op.drop_column('equipment_cost')
        batch_op.drop_column('fertilizer_cost')

    with op.batch_alter_table('yield_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('harvest_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('details', sa.String(length=400), nullable=True))
        batch_op.drop_column('harvest_dates')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yield_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('harvest_dates', sa.TEXT(), nullable=True))
        batch_op.drop_column('details')
        batch_op.drop_column('harvest_date')

    with op.batch_alter_table('financial_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fertilizer_cost', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('equipment_cost', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('seed_cost', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('pesticide_cost', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('labor_cost', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('revenue', sa.FLOAT(), nullable=True))
        batch_op.drop_column('date')
        batch_op.drop_column('details')
        batch_op.drop_column('amount')
        batch_op.drop_column('cost_type')

    with op.batch_alter_table('cropcycle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('harvest_dates', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('planting_dates', sa.TEXT(), nullable=True))
        batch_op.drop_column('expecetd_harvest_date')
        batch_op.drop_column('planting_date')

    with op.batch_alter_table('crop_management', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
