"""Add fertilizer_type column to crop_management

Revision ID: 8bfed1e49192
Revises: 
Create Date: 2024-08-07 11:09:16.455341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bfed1e49192'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    with op.batch_alter_table('crop_management', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fertilizer_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fertilizer_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fertilizer_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('irrigation_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('irrigation_amount', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('control_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('control_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('control_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('weeding_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('weeding_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('tasks_completed', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('hours_accrued', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('labour_date', sa.Date(), nullable=True))
        batch_op.drop_column('date')
        batch_op.drop_column('type')
        batch_op.drop_column('details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crop_management', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=True))
        batch_op.drop_column('labour_date')
        batch_op.drop_column('hours_accrued')
        batch_op.drop_column('tasks_completed')
        batch_op.drop_column('weeding_date')
        batch_op.drop_column('weeding_method')
        batch_op.drop_column('control_date')
        batch_op.drop_column('control_amount')
        batch_op.drop_column('control_type')
        batch_op.drop_column('irrigation_amount')
        batch_op.drop_column('irrigation_type')
        batch_op.drop_column('fertilizer_date')
        batch_op.drop_column('fertilizer_amount')
        batch_op.drop_column('fertilizer_type')

    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('farm_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('region', sa.VARCHAR(length=255), nullable=False),
    sa.Column('traditional_authority', sa.VARCHAR(length=255), nullable=False),
    sa.Column('farm_size', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
