"""Changing Schema For Crop Management

Revision ID: f45bbbb5a1b2
Revises: a819bf93b240
Create Date: 2024-10-01 16:29:23.824925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45bbbb5a1b2'
down_revision = 'a819bf93b240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crop_management', schema=None) as batch_op:
        batch_op.add_column(sa.Column('management_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('details', sa.String(length=200), nullable=True))
        batch_op.drop_column('hours_accrued')
        batch_op.drop_column('irrigation_amount')
        batch_op.drop_column('fertilizer_date')
        batch_op.drop_column('irrigation_type')
        batch_op.drop_column('control_type')
        batch_op.drop_column('weeding_method')
        batch_op.drop_column('labour_date')
        batch_op.drop_column('irrigation_date')
        batch_op.drop_column('tasks_completed')
        batch_op.drop_column('fertilizer_amount')
        batch_op.drop_column('fertilizer_type')
        batch_op.drop_column('weeding_date')
        batch_op.drop_column('control_date')
        batch_op.drop_column('control_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crop_management', schema=None) as batch_op:
        batch_op.add_column(sa.Column('control_amount', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('control_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('weeding_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('fertilizer_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('fertilizer_amount', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('tasks_completed', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('irrigation_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('labour_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('weeding_method', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('control_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('irrigation_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('fertilizer_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('irrigation_amount', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('hours_accrued', sa.FLOAT(), nullable=True))
        batch_op.drop_column('details')
        batch_op.drop_column('date')
        batch_op.drop_column('amount')
        batch_op.drop_column('management_type')

    # ### end Alembic commands ###
